CREATE DATABASE IF NOT EXISTS nexus_db;
USE nexus_db;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(100) NOT NULL
);

CREATE TABLE atendimentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente VARCHAR(100),
  mensagem TEXT,
  data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
